service: minionbot
app: minionbot
tenant: vwooosh

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
  
functions:
  handler:
    handler: handler.handler
    layers:
      - {Ref: LibsLambdaLayer}
    
    events: #Quais eventos ele vai ouvir
      - http:
          path: /
          method: post
          cors: true        
     
  
  testBd:
    handler: handler.getAllMinions
    layers:
      - {Ref: LibsLambdaLayer}
    events:
      - http:
          path: minions
          method: get
          cors: true
  
layers:
  libs:
    path: layer
    compatibleRuntimes:
      - nodejs10.x

plugins:
  - serverless-dynamodb-local
  - serverless-plugin-include-dependencies